version: "3.9"
services:
  api_server:
    container_name: api_server
    build:
      context: ./api-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-server:/app
    ports:
      - 4000:4000
      - 4100:4100
    depends_on:
      - db
    tty: true # コンテナの永続化
    environment:
      - TZ=Asia/Tokyo

  db:
    image: mysql:8.0.36
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: request_form_app
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql

  localstack:
    image: localstack/localstack
    ports:
      - 8080:8080 # dashboard
      - 4566:4566 # edge port
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: ap-northeast-1
      PERSISTENCE: 1
    volumes:
      - ./docker/localstack/:/etc/localstack/init/ready.d

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    ports:
      - 3000:3000
      - 3100:3100
    volumes:
      - ./client:/app
    restart: always
    tty: true
    stdin_open: true
    command: "bash entrypoint.sh"
