/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Request Form App Service
 * request form app APIs
 * OpenAPI spec version: 1.0
 */

export interface UserSignInResponse {
  token: string;
  error: string;
}
