FROM ruby:3.4.5

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs default-mysql-client

RUN mkdir /app

WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN bundle install

COPY . /app

CMD sh -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"