name: Client Lint

on:
  pull_request:
    paths:
      - "client/**/*js"
      - "client/**/*mjs"
      - "client/**/*ts"
      - "client/**/*tsx"
      - "client/**/package.json"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 9

      - name: Install dependencies
        working-directory: ./client
        run: pnpm i

      - name: Generate reviewdog api token
        id: generate_token
        uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1.9.0
        with:
          app_id: ${{ secrets.REVIEDOG_APP_ID }}
          private_key: ${{ secrets.REVIEDOG_PRIVATE_KEY }}

      - name: Setup reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2

      - name: Run tsc(type check) with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ steps.generate_token.outputs.token }}
        working-directory: ./client
        run: pnpm typecheck | reviewdog -reporter=github-pr-review -f=tsc -level=warn -filter-mode=nofilter -fail-level=any
        shell: bash

      - name: Run prettier
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ steps.generate_token.outputs.token }}
        working-directory: ./client
        run: pnpm format:check | reviewdog -reporter=github-pr-review -f=eslint -level=warn -filter-mode=nofilter -fail-level=any
        shell: bash

      - name: Run eslint with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ steps.generate_token.outputs.token }}
        working-directory: ./client
        run: pnpm lint | reviewdog -reporter=github-pr-review -f=eslint -level=warn -filter-mode=nofilter -fail-level=any
        shell: bash
